import { CommonTemplateProps } from '../interface/index'
import iconData from '../config/iconConfig.json'

// Template for producing React component with prop selectable SVG version OUTLINE/FILLED
function componentCommonTemplate ({ fileName, filled, outlined }:CommonTemplateProps) {
  const render = `
// GENERATED BY ./scripts/iconScript.ts

import { FunctionalComponent } from 'vue';
import { IconCommonProps, valuesMap } from '../helper';
import { flipFunction } from '../flipFunction';

export interface EOS_${fileName}IconType extends FunctionalComponent<IconCommonProps> {
    displayName: string;
  }

const EOS_${fileName}: EOS_${fileName}IconType = ({size = "${iconData.iconDefault.size}", color = "${iconData.iconDefault.color}", rotate = ${iconData.iconDefault.rotate}, horizontalFlip = ${iconData.iconDefault.horizontalFlip}, verticalFlip = ${iconData.iconDefault.verticalFlip}, theme = "${iconData.iconDefault.theme}"}) => {
    const sizeString: string = size.toString()
    if(Object.keys(valuesMap).includes(sizeString)) {
        size = valuesMap[size]
    }
    const { scaleX, scaleY, translateX, translateY } = flipFunction({horizontalFlip,verticalFlip})
return (
    <>
    {
        (theme === "filled") &&
        // Filled version
        ${filled}
    }
    {
        (theme === "outlined") &&
        // Outlined version
        ${outlined}
    }
    </>
    );
};

EOS_${fileName}.displayName = 'EOS_${fileName}';
export default EOS_${fileName};
`
  return (render)
}

export default componentCommonTemplate
