import { TemplateProps } from '../interface/index'
import iconData from '../config/iconConfig.json'

function componentTemplate ({ fileName, data }:TemplateProps) {
  const render = `
// GENERATED BY ./scripts/iconScript.ts

import { FunctionalComponent } from 'vue';
import { IconProps, valuesMap } from '../helper';
import { flipFunction } from '../flipFunction';

export interface EOS_${fileName}IconType extends FunctionalComponent<IconProps> {
  displayName: string;
}

const EOS_${fileName}: EOS_${fileName}IconType = ({size = "${iconData.iconDefault.size}", color = "${iconData.iconDefault.color}", rotate = ${iconData.iconDefault.rotate}, horizontalFlip = ${iconData.iconDefault.horizontalFlip}, verticalFlip = ${iconData.iconDefault.verticalFlip}}) => {
  const sizeString: string = size.toString()
  if(Object.keys(valuesMap).includes(sizeString)) {
      size = valuesMap[size]
  }
  const { scaleX, scaleY, translateX, translateY } = flipFunction({horizontalFlip,verticalFlip})
  return (
    ${data}
    )
};

EOS_${fileName}.displayName = 'EOS_${fileName}';
export default EOS_${fileName};
`
  return (render)
}

export default componentTemplate
